config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }, skip: [:sessions], controller: { registrations: "user_registrations"}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
    get 'devise/registrations/confirmation_is_sent'
  end

  resources :products do
    resources :comments
  end
  resources :users

  resources :orders, only: [:index, :show, :create, :destroy]

  get 'simple_pages/landing_page'

  get 'simple_pages/what'

  get 'simple_pages/coaching'

  get 'simple_pages/login'

  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  root 'simple_pages#landing_page'

  post 'simple_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nameofapp</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>


  <body data-spy="scroll" data-target=".navbar">
  <div id="wrap">
    <nav class="navbar navigation-wrapper navbar-inverse" role="navigation">
     <div class="container-fluid container-nav-bar">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-menu" aria-expanded="false">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
          <span class="icon-bar"></span>
         </button>
       </div>
       <div class="navbar-collapse collapse">
         <ul class="navbar-left">
          <!-- Search -->
          <li>
            <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
            <%= form.text_field :q, id: 'q', value: params[:q], class: "form-control", placeholder: "What can I find for you?" %>
          </li>
          <li>
            <%= form.submit 'Search', class: 'btn btn-success'%>
            <% end %>
          </li>
        </ul>
         <ul>
           <li><%= link_to "Home", root_path, class:"nav-link" %></li>
           <li><%= link_to "Who", simple_pages_about_path, class:"nav-link" %></li>
           <li><%= link_to "What", simple_pages_what_path, class:"nav-link" %></li>
           <li><%= link_to "Coaching", simple_pages_coaching_path, class:"nav-link" %></li>
           <li><%= link_to "Contact", simple_pages_contact_path, class:"nav-link" %></li>
           <li><%= link_to "Products", products_path, class:"nav-link" %></li>
           <li class="login">
             <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
             <% else %>
              <%= link_to('Login', new_user_session_path) %>
             <% end %>
           </li>
         </ul>
       </div>
     </div>
   </nav>

   <section class="container-fluid">

     <!-- Flash Notice Tags -->
     <% if notice %>
       <p id="notice" class="alert alert-success" role="alert"><%= notice %></p>
     <% end %>

     <% if alert %>
       <p id="alert" class="alert alert-danger" role="alert"><%= alert %></p>
     <% end %>

  </section>

  <%= yield %>
  <div id="push"></div>
</div>

  <footer class="navbar-fixed-bottom container-fluid copy-right" id="footer">
    &copy; Kate Huggins, Transience LLC 2018
  </footer>

  </body>
</html>